apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.name" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4317
      targetPort: http
      protocol: TCP
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
